CREATE OR REPLACE PROCEDURE procGuardarInformacaoSemanal(D DATE) AS
    V_ARRAY SYS_REFCURSOR;
    MATRICULA VEICULOS.MATRICULA%TYPE;
    M VEICULOS.MATRICULA%TYPE;
    DATA_I VEICULOS_CONDUTORES.DATA_INICIO%TYPE;
    DATA_f VEICULOS_CONDUTORES.DATA_FIM%TYPE;
    N_VIAGENS INTEGER;
    N_KM INTEGER;
    DURACAO INTEGER;
    N_VEICULOS INTEGER;
    TOTAL_VEICULOS INTEGER;
BEGIN
    V_ARRAY := funcObterInfoSemanalVeiculos(D);

    DBMS_OUTPUT.PUT_LINE('RESUMO DAS INFORMAÇÕES DOS VEÍCULOS:');
    DBMS_OUTPUT.PUT_LINE('INSTANTE - MATRICULA - DATA INICIO - DATA FIM - Nº VIAGENS - Nº KM - TOTAL DURACAO');
    LOOP
        FETCH V_ARRAY INTO MATRICULA, DATA_I, DATA_F, N_VIAGENS, N_KM, DURACAO;
        EXIT WHEN V_ARRAY%NOTFOUND;
        INSERT INTO RESUMOSVEICULOS VALUES (SYSDATE, MATRICULA, DATA_I, DATA_F, N_VIAGENS, N_KM, DURACAO);
        DBMS_OUTPUT.PUT_LINE(SYSDATE || ' - ' || MATRICULA || ' - ' || DATA_I || ' - ' || DATA_F || ' - ' || N_VIAGENS || ' - ' || N_KM || ' - ' || DURACAO);
    end loop;
    SELECT COUNT(*) INTO N_VEICULOS FROM RESUMOSVEICULOS;
    SELECT COUNT(*) INTO TOTAL_VEICULOS FROM VEICULOS;
    DBMS_OUTPUT.PUT_LINE('PERCENTAGEM DE VEICULOS QUE FIZERAM VIAGENS ESTA SEMANA: ' || N_VEICULOS/TOTAL_VEICULOS);
    DBMS_OUTPUT.PUT_LINE('LISTA DE VEICULOS:');
    FOR M IN (SELECT MATRICULA FROM RESUMOSVEICULOS)
    LOOP
        DBMS_OUTPUT.PUT_LINE(M);
    end loop;
    DBMS_OUTPUT.PUT_LINE('PERCENTAGEM DE VEICULOS QUE NÃO FIZERAM VIAGENS ESTA SEMANA: ' || (TOTAL_VEICULOS - N_VEICULOS)/TOTAL_VEICULOS);
    DBMS_OUTPUT.PUT_LINE('LISTA DE VEICULOS:');
    FOR M IN (SELECT MATRICULA FROM RESUMOSVEICULOS MINUS SELECT MATRICULA FROM VEICULOS)
    LOOP
        DBMS_OUTPUT.PUT_LINE(M);
    end loop;
end;